// Package hooks installs git pre-commit hooks.
package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// Mode determines which hooks to install.
type Mode string

const (
	ModeLight  Mode = "light"
	ModeStrict Mode = "strict"
	ModeCustom Mode = "custom"
)

// EnsureGitRepo checks that .git directory exists.
func EnsureGitRepo() error {
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		return fmt.Errorf("not a git repository: .git directory not found")
	}
	return nil
}

// HookPath returns the path to .git/hooks/pre-commit.
func HookPath() string {
	return filepath.Join(".git", "hooks", "pre-commit")
}

// Render generates the pre-commit hook script content for the given mode and stack.
func Render(mode Mode, stack string) string {
	var sb string

	if runtime.GOOS == "windows" {
		sb = "#!/bin/sh\n# scaf pre-commit hook\nset -e\n\n"
	} else {
		sb = "#!/bin/sh\n# scaf pre-commit hook — generated by scaf\n# https://github.com/TerraFaster/scaf\nset -e\n\n"
	}

	switch mode {
	case ModeLight:
		sb += lightHook(stack)
	case ModeStrict:
		sb += strictHook(stack)
	default:
		sb += lightHook(stack)
	}

	return sb
}

func lightHook(stack string) string {
	base := `# ── Basic checks ──────────────────────────────────────────────
echo "Running pre-commit checks..."

# Check for trailing whitespace
if git diff --cached --check; then
  echo "✔ No whitespace errors"
else
  echo "✖ Whitespace errors found"
  exit 1
fi

`
	switch stack {
	case "go":
		base += `# ── Go checks ─────────────────────────────────────────────────
if command -v gofmt >/dev/null 2>&1; then
  FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)
  if [ -n "$FILES" ]; then
    UNFORMATTED=$(gofmt -l $FILES)
    if [ -n "$UNFORMATTED" ]; then
      echo "✖ Go files not formatted:"
      echo "$UNFORMATTED"
      echo "  Run: gofmt -w ."
      exit 1
    fi
    echo "✔ gofmt OK"
  fi
fi

if command -v go >/dev/null 2>&1; then
  go vet ./... && echo "✔ go vet OK"
fi
`
	case "node":
		base += `# ── Node checks ───────────────────────────────────────────────
if [ -f "node_modules/.bin/prettier" ]; then
  node_modules/.bin/prettier --check . && echo "✔ prettier OK"
fi

if [ -f "node_modules/.bin/eslint" ]; then
  node_modules/.bin/eslint . && echo "✔ eslint OK"
fi
`
	}

	base += "\necho \"✔ Pre-commit checks passed\"\n"
	return base
}

func strictHook(stack string) string {
	base := `# ── Basic checks ──────────────────────────────────────────────
echo "Running strict pre-commit checks..."

# Check for trailing whitespace
if git diff --cached --check; then
  echo "✔ No whitespace errors"
else
  echo "✖ Whitespace errors found"
  exit 1
fi

# Scan for secrets (basic patterns)
if git diff --cached | grep -iE '(password|secret|api_key|token)\s*=\s*["\x27][^"\x27]{8,}'; then
  echo "✖ Potential secret detected in staged changes"
  exit 1
fi
echo "✔ No obvious secrets found"

`
	switch stack {
	case "go":
		base += `# ── Go strict checks ─────────────────────────────────────────
if command -v gofmt >/dev/null 2>&1; then
  FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)
  if [ -n "$FILES" ]; then
    UNFORMATTED=$(gofmt -l $FILES)
    if [ -n "$UNFORMATTED" ]; then
      echo "✖ Go files not formatted: $UNFORMATTED"
      exit 1
    fi
    echo "✔ gofmt OK"
  fi
fi

if command -v go >/dev/null 2>&1; then
  go vet ./... && echo "✔ go vet OK"
fi

if command -v golangci-lint >/dev/null 2>&1; then
  golangci-lint run && echo "✔ golangci-lint OK"
fi
`
	case "node":
		base += `# ── Node strict checks ───────────────────────────────────────
if [ -f "node_modules/.bin/prettier" ]; then
  node_modules/.bin/prettier --check . && echo "✔ prettier OK"
fi

if [ -f "node_modules/.bin/eslint" ]; then
  node_modules/.bin/eslint . && echo "✔ eslint OK"
fi

if [ -f "node_modules/.bin/commitlint" ]; then
  echo "$(git log -1 --pretty=%B)" | node_modules/.bin/commitlint && echo "✔ commitlint OK"
fi
`
	}

	base += "\necho \"✔ All strict pre-commit checks passed\"\n"
	return base
}

// Install writes the hook file and makes it executable.
func Install(content, path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("cannot create hooks dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write hook: %w", err)
	}
	return nil
}
