name: WinGet Release

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  winget:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Submit WinGet PR
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: TerraFaster.scaf
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ github.event.workflow_run.head_branch }}
  