name: WinGet Release

on:
  release:
    types: [published]

jobs:
  winget:
    name: Submit to WinGet
    runs-on: windows-latest
    steps:
      - name: Submit WinGet PR
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: TerraFaster.scaf
          token: ${{ secrets.WINGET_TOKEN }}
